version: '3'

services:
  web:
    build:
        context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/backend
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on: 
      - db

  db:
    image: postgres
    environment:
        POSTGRES_USER: homestead
        POSTGRES_DB: homestead
        POSTGRES_PASSWORD: secret

    ports:
        - "5432:5432"
    volumes:
        - pgdata:/var/lib/postgresql/data
    env_file:
        - .env

volumes:
    pgdata:
